import TodosList from "../components/TodosList"

export const metadata = {
  title: 'Todos Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <main className="flex">
            <div className="">
                <TodosList />
            </div>
            <div className="flex-1">
                {children}
            </div>
        </main>
      </body>
    </html>
  )
}