import Search from "../components/Search"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <main className="flex space-x-6 divide-x-4 p-6">
          <div className="">
            Search here
          </div>
          <div className="flex-1 pl-6">
            <Search />
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}