import './globals.css'
import Navbar from './components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className='container mx-auto p-9 pt-0' data-theme="dark">
        <Navbar />
        {children}
      </body>
    </html>
  )
}