import './globals.css'
import Navbar from './components/Navbar'

export const metadata = {
  title: 'The Next Prisma todo app',
  description: 'Generated by create next app',

  openGraph: {
    title: 'Next.js opengraph tag',
    url: 'https://nextjs.org',
    images: [
      {
        url: 'https://nextjs.org/og.png',
        width: 800,
        height: 600,
      },
    ],
  },
  robots: {
    index: true,
  },
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className='container mx-auto p-9 pt-0' data-theme="light">
        <Navbar />
        {children}
      </body>
    </html>
  )
}